### ISSUE TITLE
Prompt users to choose a license

### ISSUE THREAD

**Issue by strugee** [bespokejs/generator-bespoke#45] opened 2017-01-06 19:13 UTC
I'm guessing a lot of users would choose to license (some) presentations under Creative Commons or somesuch, but didn't think to do so. It would be awesome if generator-bespoke would prompt the user to do this.

**Comment by mojavelinux** [comment] 2017-01-06 20:59
We were trying to minimize the number of questions to ask...though this one does seem reasonable. @hsablonniere thoughts?

**Comment by mojavelinux** [comment] 2017-09-17 06:56
I don't really like how this is implemented in NPM. It asks for a textual response. The problem is, most people don't know the licenses by their short codes. And if we present a list, it will be inherently incomplete. I also don't want to force anyone into a license. npm does this and I don't like it (they default to ISC, which is akin to MIT).

If we do present a default option, I think it would have to be UNLICENSED, which is actually the default anyway if you don't specify it. In that case, I would be fine with requiring knowledge of the short codes, since you have to know the licenses to choose one.

**Comment by mojavelinux** [comment] 2017-09-17 06:57
I realize that argument sounded confusing. If we use UNLICENSED as the default and allow a textual input, then I'm okay with adding this option.

**Closed** 2017-09-18 06:58 UTC
Labels: enhancement
